name: lint

on:
  push:
    branches: [ main ]


jobs:
  lint:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Clippy
        run: rustup component add clippy

      - name: Cargo Check
        run: cargo check

      - name: Cargo Clippy
        run: cargo clippy
